In [71]:
import pandas as pd

In [72]:
dataset=pd.read_csv("spam.csv",encoding='ISO-8859-1')

In [73]:
dataset

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [74]:
dataset=dataset.iloc[:,:2]

In [75]:
dataset

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [76]:
df=dataset

In [77]:
df.columns

Index(['v1', 'v2'], dtype='object')

In [78]:
x=df.v2
y=df.v1


In [79]:
from sklearn.preprocessing import LabelEncoder

In [80]:
le=LabelEncoder()
y=le.fit_transform(y)
y=y.reshape(-1,1)

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15)

In [83]:
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences

In [84]:
max_w=1000
max_len=150
tok=Tokenizer(num_words=max_w)
tok.fit_on_texts(x_train)
sequences=tok.texts_to_sequences(x_train)
sequences_matrix=pad_sequences(sequences,maxlen=max_len)

In [85]:

#create models
from keras.layers import LSTM,Activation,Dense,Dropout,Input,Embedding
from keras.models import Model
inputs=Input(name='inputs',shape=[max_len])
layer=Embedding(max_w,50,input_length=max_len)(inputs)
layer=LSTM(64)(layer)


In [86]:
layer=Dense(256,name='FC1')(layer)
layer=Activation('relu')(layer)
layer=Dropout(0.5)(layer)
layer=Dense(1,name='out_layer')(layer)
layer=Activation('sigmoid')(layer)
model=Model(inputs=inputs,outputs=layer)
model.summary()


Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 inputs (InputLayer)         [(None, 150)]             0         
                                                                 
 embedding_4 (Embedding)     (None, 150, 50)           50000     
                                                                 
 lstm_4 (LSTM)               (None, 64)                29440     
                                                                 
 FC1 (Dense)                 (None, 256)               16640     
                                                                 
 activation_9 (Activation)   (None, 256)               0         
                                                                 
 dropout_5 (Dropout)         (None, 256)               0         
                                                                 
 out_layer (Dense)           (None, 1)                 257 

In [87]:
from keras.optimizers import RMSprop
model.compile(loss='binary_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

In [88]:
model.fit(sequences_matrix,y_train,batch_size=128,epochs=10,validation_split=0.2)

Epoch 1/10
30/30 [==============================] - 20s 589ms/step - loss: 0.3218 - accuracy: 0.8788 - val_loss: 0.1371 - val_accuracy: 0.9620
Epoch 2/10
30/30 [==============================] - 11s 367ms/step - loss: 0.0839 - accuracy: 0.9784 - val_loss: 0.0458 - val_accuracy: 0.9863
Epoch 3/10
30/30 [==============================] - 8s 283ms/step - loss: 0.0468 - accuracy: 0.9868 - val_loss: 0.0452 - val_accuracy: 0.9873
Epoch 4/10
30/30 [==============================] - 9s 284ms/step - loss: 0.0362 - accuracy: 0.9889 - val_loss: 0.0362 - val_accuracy: 0.9895
Epoch 5/10
30/30 [==============================] - 8s 284ms/step - loss: 0.0269 - accuracy: 0.9921 - val_loss: 0.0355 - val_accuracy: 0.9905
Epoch 6/10
30/30 [==============================] - 9s 285ms/step - loss: 0.0217 - accuracy: 0.9934 - val_loss: 0.0471 - val_accuracy: 0.9842
Epoch 7/10
30/30 [==============================] - 8s 283ms/step - loss: 0.0149 - accuracy: 0.9960 - val_loss: 0.0422 - val_accuracy: 0.9905
Epoc

In [89]:
#saving the model
model.save('spamm.h5')

In [90]:
#tok.fit_on_texts(x_test)
#test dataset

In [91]:
test_sequences=tok.texts_to_sequences(x_test)
print(test_sequences)

[[46, 98, 42, 8, 12, 269, 3, 17, 43, 510, 3, 17, 102, 16, 90, 18, 2, 12, 510, 7], [355, 83, 230, 674], [134, 4, 408, 451, 8, 127, 9, 327, 947, 972, 3, 485, 33, 23, 127, 126, 139, 273, 9, 4, 61, 327, 209, 35, 54, 19, 886, 63, 892], [7, 101, 101, 676], [72, 757, 50, 72, 10, 72, 187, 31, 229, 7, 10, 7, 59, 1, 294, 389, 4, 366, 46, 124], [106, 10, 236, 3, 9, 615, 53, 54, 2, 33, 21], [255, 799, 14, 38, 23, 100, 510, 18, 3, 86, 10], [3, 507, 12, 134], [99, 38, 241, 4, 15, 164, 9, 501, 7, 1, 242, 106, 30, 732, 304, 26, 38], [3, 82, 2, 33, 44, 21], [4, 187, 31, 82, 725, 15, 7, 203, 105, 688, 15], [230, 37, 334], [7, 991, 3, 7, 1, 83, 39, 29, 87, 44, 135], [191, 66, 24, 62, 1, 152, 26], [23, 110, 31, 89, 825, 452, 601], [302, 8, 5, 659, 5, 288, 58, 18, 41, 40, 974, 71, 265, 54, 22, 663, 384, 876], [56, 425, 11, 66, 49, 469, 12, 61, 49, 118, 3, 232, 1, 130, 12, 109, 11, 781, 1, 112, 15, 3], [136, 144, 54, 483, 723], [188, 39, 22, 297, 2, 195, 6, 556, 325, 353, 19, 3, 17, 173, 4, 147, 262, 16, 46

In [92]:
test_sequences_matrix=pad_sequences(test_sequences,maxlen=max_len)

In [93]:
print(test_sequences_matrix)

[[  0   0   0 ...  12 510   7]
 [  0   0   0 ...  83 230 674]
 [  0   0   0 ... 886  63 892]
 ...
 [  0   0   0 ... 169   3  27]
 [  0   0   0 ...   4 796 418]
 [  0   0   0 ...  72 185  10]]


In [94]:
accr=model.evaluate(test_sequences_matrix,y_test)

27/27 [==============================] - 1s 25ms/step - loss: 0.0978 - accuracy: 0.9785
